export const EVENTS = {
  SELECTION: {
    CHANGE: "SELECTION_CHANGE_EVENT",
  },
  GLOBAL: {
    READY: "EDITOR_READY_EVENT",
    CHANGE: "EDITOR_CONTENT_CHANGE",
  },
  FORMAT: {
    CLICK: "FORMAT_CLICK_EVENT",
    DONE: "FORMAT_CLICK_DONE",
  },
  ACTION: {
    CLICK: "ACTION_CLICK_EVENT",
  },
};
